/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopNewRouteImport } from './routes/shop/new'
import { Route as ShopAdminRouteImport } from './routes/shop/_admin'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as AdminAdminLayoutRouteImport } from './routes/admin/_adminLayout'
import { Route as UserAccountProfileRouteImport } from './routes/user/account/profile'
import { Route as ShopAdminAdminLayoutRouteImport } from './routes/shop/_admin/_adminLayout'
import { Route as AdminAdminLayoutDashboardRouteImport } from './routes/admin/_adminLayout/dashboard'
import { Route as AdminAdminLayoutCategoriesRouteImport } from './routes/admin/_adminLayout/categories'
import { Route as AdminAdminLayoutAdvertisementsRouteImport } from './routes/admin/_adminLayout/advertisements'
import { Route as ShopAdminAdminLayoutAdminTransactionsRouteImport } from './routes/shop/_admin/_adminLayout/admin/transactions'
import { Route as ShopAdminAdminLayoutAdminSettingsRouteImport } from './routes/shop/_admin/_adminLayout/admin/settings'
import { Route as ShopAdminAdminLayoutAdminDashboardRouteImport } from './routes/shop/_admin/_adminLayout/admin/dashboard'
import { Route as ShopAdminAdminLayoutAdminProductIndexRouteImport } from './routes/shop/_admin/_adminLayout/admin/product/index'
import { Route as ShopAdminAdminLayoutAdminProductNewRouteImport } from './routes/shop/_admin/_adminLayout/admin/product/new'
import { Route as ShopAdminAdminLayoutAdminProductEditRouteImport } from './routes/shop/_admin/_adminLayout/admin/product/edit'
import { Route as ShopAdminAdminLayoutAdminProductVariantIdRouteImport } from './routes/shop/_admin/_adminLayout/admin/product/variant/$id'
import { Route as ShopAdminAdminLayoutAdminProductStokIdRouteImport } from './routes/shop/_admin/_adminLayout/admin/product/stok/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNewRoute = ShopNewRouteImport.update({
  id: '/shop/new',
  path: '/shop/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAdminRoute = ShopAdminRouteImport.update({
  id: '/shop/_admin',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLayoutRoute = AdminAdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => AdminRoute,
} as any)
const UserAccountProfileRoute = UserAccountProfileRouteImport.update({
  id: '/user/account/profile',
  path: '/user/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAdminAdminLayoutRoute = ShopAdminAdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => ShopAdminRoute,
} as any)
const AdminAdminLayoutDashboardRoute =
  AdminAdminLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)
const AdminAdminLayoutCategoriesRoute =
  AdminAdminLayoutCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)
const AdminAdminLayoutAdvertisementsRoute =
  AdminAdminLayoutAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminTransactionsRoute =
  ShopAdminAdminLayoutAdminTransactionsRouteImport.update({
    id: '/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminSettingsRoute =
  ShopAdminAdminLayoutAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminDashboardRoute =
  ShopAdminAdminLayoutAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminProductIndexRoute =
  ShopAdminAdminLayoutAdminProductIndexRouteImport.update({
    id: '/admin/product/',
    path: '/admin/product/',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminProductNewRoute =
  ShopAdminAdminLayoutAdminProductNewRouteImport.update({
    id: '/admin/product/new',
    path: '/admin/product/new',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminProductEditRoute =
  ShopAdminAdminLayoutAdminProductEditRouteImport.update({
    id: '/admin/product/edit',
    path: '/admin/product/edit',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminProductVariantIdRoute =
  ShopAdminAdminLayoutAdminProductVariantIdRouteImport.update({
    id: '/admin/product/variant/$id',
    path: '/admin/product/variant/$id',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)
const ShopAdminAdminLayoutAdminProductStokIdRoute =
  ShopAdminAdminLayoutAdminProductStokIdRouteImport.update({
    id: '/admin/product/stok/$id',
    path: '/admin/product/stok/$id',
    getParentRoute: () => ShopAdminAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminLayoutRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopAdminAdminLayoutRouteWithChildren
  '/shop/new': typeof ShopNewRoute
  '/admin/advertisements': typeof AdminAdminLayoutAdvertisementsRoute
  '/admin/categories': typeof AdminAdminLayoutCategoriesRoute
  '/admin/dashboard': typeof AdminAdminLayoutDashboardRoute
  '/user/account/profile': typeof UserAccountProfileRoute
  '/shop/admin/dashboard': typeof ShopAdminAdminLayoutAdminDashboardRoute
  '/shop/admin/settings': typeof ShopAdminAdminLayoutAdminSettingsRoute
  '/shop/admin/transactions': typeof ShopAdminAdminLayoutAdminTransactionsRoute
  '/shop/admin/product/edit': typeof ShopAdminAdminLayoutAdminProductEditRoute
  '/shop/admin/product/new': typeof ShopAdminAdminLayoutAdminProductNewRoute
  '/shop/admin/product/': typeof ShopAdminAdminLayoutAdminProductIndexRoute
  '/shop/admin/product/stok/$id': typeof ShopAdminAdminLayoutAdminProductStokIdRoute
  '/shop/admin/product/variant/$id': typeof ShopAdminAdminLayoutAdminProductVariantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminLayoutRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopAdminAdminLayoutRouteWithChildren
  '/shop/new': typeof ShopNewRoute
  '/admin/advertisements': typeof AdminAdminLayoutAdvertisementsRoute
  '/admin/categories': typeof AdminAdminLayoutCategoriesRoute
  '/admin/dashboard': typeof AdminAdminLayoutDashboardRoute
  '/user/account/profile': typeof UserAccountProfileRoute
  '/shop/admin/dashboard': typeof ShopAdminAdminLayoutAdminDashboardRoute
  '/shop/admin/settings': typeof ShopAdminAdminLayoutAdminSettingsRoute
  '/shop/admin/transactions': typeof ShopAdminAdminLayoutAdminTransactionsRoute
  '/shop/admin/product/edit': typeof ShopAdminAdminLayoutAdminProductEditRoute
  '/shop/admin/product/new': typeof ShopAdminAdminLayoutAdminProductNewRoute
  '/shop/admin/product': typeof ShopAdminAdminLayoutAdminProductIndexRoute
  '/shop/admin/product/stok/$id': typeof ShopAdminAdminLayoutAdminProductStokIdRoute
  '/shop/admin/product/variant/$id': typeof ShopAdminAdminLayoutAdminProductVariantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/_adminLayout': typeof AdminAdminLayoutRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/_admin': typeof ShopAdminRouteWithChildren
  '/shop/new': typeof ShopNewRoute
  '/admin/_adminLayout/advertisements': typeof AdminAdminLayoutAdvertisementsRoute
  '/admin/_adminLayout/categories': typeof AdminAdminLayoutCategoriesRoute
  '/admin/_adminLayout/dashboard': typeof AdminAdminLayoutDashboardRoute
  '/shop/_admin/_adminLayout': typeof ShopAdminAdminLayoutRouteWithChildren
  '/user/account/profile': typeof UserAccountProfileRoute
  '/shop/_admin/_adminLayout/admin/dashboard': typeof ShopAdminAdminLayoutAdminDashboardRoute
  '/shop/_admin/_adminLayout/admin/settings': typeof ShopAdminAdminLayoutAdminSettingsRoute
  '/shop/_admin/_adminLayout/admin/transactions': typeof ShopAdminAdminLayoutAdminTransactionsRoute
  '/shop/_admin/_adminLayout/admin/product/edit': typeof ShopAdminAdminLayoutAdminProductEditRoute
  '/shop/_admin/_adminLayout/admin/product/new': typeof ShopAdminAdminLayoutAdminProductNewRoute
  '/shop/_admin/_adminLayout/admin/product/': typeof ShopAdminAdminLayoutAdminProductIndexRoute
  '/shop/_admin/_adminLayout/admin/product/stok/$id': typeof ShopAdminAdminLayoutAdminProductStokIdRoute
  '/shop/_admin/_adminLayout/admin/product/variant/$id': typeof ShopAdminAdminLayoutAdminProductVariantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/sign-in'
    | '/sign-up'
    | '/product/$id'
    | '/shop/$slug'
    | '/shop'
    | '/shop/new'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/user/account/profile'
    | '/shop/admin/dashboard'
    | '/shop/admin/settings'
    | '/shop/admin/transactions'
    | '/shop/admin/product/edit'
    | '/shop/admin/product/new'
    | '/shop/admin/product/'
    | '/shop/admin/product/stok/$id'
    | '/shop/admin/product/variant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/sign-in'
    | '/sign-up'
    | '/product/$id'
    | '/shop/$slug'
    | '/shop'
    | '/shop/new'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/user/account/profile'
    | '/shop/admin/dashboard'
    | '/shop/admin/settings'
    | '/shop/admin/transactions'
    | '/shop/admin/product/edit'
    | '/shop/admin/product/new'
    | '/shop/admin/product'
    | '/shop/admin/product/stok/$id'
    | '/shop/admin/product/variant/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/sign-in'
    | '/sign-up'
    | '/admin/_adminLayout'
    | '/product/$id'
    | '/shop/$slug'
    | '/shop/_admin'
    | '/shop/new'
    | '/admin/_adminLayout/advertisements'
    | '/admin/_adminLayout/categories'
    | '/admin/_adminLayout/dashboard'
    | '/shop/_admin/_adminLayout'
    | '/user/account/profile'
    | '/shop/_admin/_adminLayout/admin/dashboard'
    | '/shop/_admin/_adminLayout/admin/settings'
    | '/shop/_admin/_adminLayout/admin/transactions'
    | '/shop/_admin/_adminLayout/admin/product/edit'
    | '/shop/_admin/_adminLayout/admin/product/new'
    | '/shop/_admin/_adminLayout/admin/product/'
    | '/shop/_admin/_adminLayout/admin/product/stok/$id'
    | '/shop/_admin/_adminLayout/admin/product/variant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ExploreRoute: typeof ExploreRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopAdminRoute: typeof ShopAdminRouteWithChildren
  ShopNewRoute: typeof ShopNewRoute
  UserAccountProfileRoute: typeof UserAccountProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/new': {
      id: '/shop/new'
      path: '/shop/new'
      fullPath: '/shop/new'
      preLoaderRoute: typeof ShopNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/_admin': {
      id: '/shop/_admin'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_adminLayout': {
      id: '/admin/_adminLayout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/account/profile': {
      id: '/user/account/profile'
      path: '/user/account/profile'
      fullPath: '/user/account/profile'
      preLoaderRoute: typeof UserAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/_admin/_adminLayout': {
      id: '/shop/_admin/_adminLayout'
      path: ''
      fullPath: '/shop'
      preLoaderRoute: typeof ShopAdminAdminLayoutRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/admin/_adminLayout/dashboard': {
      id: '/admin/_adminLayout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminLayoutDashboardRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/admin/_adminLayout/categories': {
      id: '/admin/_adminLayout/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminLayoutCategoriesRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/admin/_adminLayout/advertisements': {
      id: '/admin/_adminLayout/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdminLayoutAdvertisementsRouteImport
      parentRoute: typeof AdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/transactions': {
      id: '/shop/_admin/_adminLayout/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/shop/admin/transactions'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminTransactionsRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/settings': {
      id: '/shop/_admin/_adminLayout/admin/settings'
      path: '/admin/settings'
      fullPath: '/shop/admin/settings'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminSettingsRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/dashboard': {
      id: '/shop/_admin/_adminLayout/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/shop/admin/dashboard'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminDashboardRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/product/': {
      id: '/shop/_admin/_adminLayout/admin/product/'
      path: '/admin/product'
      fullPath: '/shop/admin/product/'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminProductIndexRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/product/new': {
      id: '/shop/_admin/_adminLayout/admin/product/new'
      path: '/admin/product/new'
      fullPath: '/shop/admin/product/new'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminProductNewRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/product/edit': {
      id: '/shop/_admin/_adminLayout/admin/product/edit'
      path: '/admin/product/edit'
      fullPath: '/shop/admin/product/edit'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminProductEditRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/product/variant/$id': {
      id: '/shop/_admin/_adminLayout/admin/product/variant/$id'
      path: '/admin/product/variant/$id'
      fullPath: '/shop/admin/product/variant/$id'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminProductVariantIdRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
    '/shop/_admin/_adminLayout/admin/product/stok/$id': {
      id: '/shop/_admin/_adminLayout/admin/product/stok/$id'
      path: '/admin/product/stok/$id'
      fullPath: '/shop/admin/product/stok/$id'
      preLoaderRoute: typeof ShopAdminAdminLayoutAdminProductStokIdRouteImport
      parentRoute: typeof ShopAdminAdminLayoutRoute
    }
  }
}

interface AdminAdminLayoutRouteChildren {
  AdminAdminLayoutAdvertisementsRoute: typeof AdminAdminLayoutAdvertisementsRoute
  AdminAdminLayoutCategoriesRoute: typeof AdminAdminLayoutCategoriesRoute
  AdminAdminLayoutDashboardRoute: typeof AdminAdminLayoutDashboardRoute
}

const AdminAdminLayoutRouteChildren: AdminAdminLayoutRouteChildren = {
  AdminAdminLayoutAdvertisementsRoute: AdminAdminLayoutAdvertisementsRoute,
  AdminAdminLayoutCategoriesRoute: AdminAdminLayoutCategoriesRoute,
  AdminAdminLayoutDashboardRoute: AdminAdminLayoutDashboardRoute,
}

const AdminAdminLayoutRouteWithChildren =
  AdminAdminLayoutRoute._addFileChildren(AdminAdminLayoutRouteChildren)

interface AdminRouteChildren {
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLayoutRoute: AdminAdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopAdminAdminLayoutRouteChildren {
  ShopAdminAdminLayoutAdminDashboardRoute: typeof ShopAdminAdminLayoutAdminDashboardRoute
  ShopAdminAdminLayoutAdminSettingsRoute: typeof ShopAdminAdminLayoutAdminSettingsRoute
  ShopAdminAdminLayoutAdminTransactionsRoute: typeof ShopAdminAdminLayoutAdminTransactionsRoute
  ShopAdminAdminLayoutAdminProductEditRoute: typeof ShopAdminAdminLayoutAdminProductEditRoute
  ShopAdminAdminLayoutAdminProductNewRoute: typeof ShopAdminAdminLayoutAdminProductNewRoute
  ShopAdminAdminLayoutAdminProductIndexRoute: typeof ShopAdminAdminLayoutAdminProductIndexRoute
  ShopAdminAdminLayoutAdminProductStokIdRoute: typeof ShopAdminAdminLayoutAdminProductStokIdRoute
  ShopAdminAdminLayoutAdminProductVariantIdRoute: typeof ShopAdminAdminLayoutAdminProductVariantIdRoute
}

const ShopAdminAdminLayoutRouteChildren: ShopAdminAdminLayoutRouteChildren = {
  ShopAdminAdminLayoutAdminDashboardRoute:
    ShopAdminAdminLayoutAdminDashboardRoute,
  ShopAdminAdminLayoutAdminSettingsRoute:
    ShopAdminAdminLayoutAdminSettingsRoute,
  ShopAdminAdminLayoutAdminTransactionsRoute:
    ShopAdminAdminLayoutAdminTransactionsRoute,
  ShopAdminAdminLayoutAdminProductEditRoute:
    ShopAdminAdminLayoutAdminProductEditRoute,
  ShopAdminAdminLayoutAdminProductNewRoute:
    ShopAdminAdminLayoutAdminProductNewRoute,
  ShopAdminAdminLayoutAdminProductIndexRoute:
    ShopAdminAdminLayoutAdminProductIndexRoute,
  ShopAdminAdminLayoutAdminProductStokIdRoute:
    ShopAdminAdminLayoutAdminProductStokIdRoute,
  ShopAdminAdminLayoutAdminProductVariantIdRoute:
    ShopAdminAdminLayoutAdminProductVariantIdRoute,
}

const ShopAdminAdminLayoutRouteWithChildren =
  ShopAdminAdminLayoutRoute._addFileChildren(ShopAdminAdminLayoutRouteChildren)

interface ShopAdminRouteChildren {
  ShopAdminAdminLayoutRoute: typeof ShopAdminAdminLayoutRouteWithChildren
}

const ShopAdminRouteChildren: ShopAdminRouteChildren = {
  ShopAdminAdminLayoutRoute: ShopAdminAdminLayoutRouteWithChildren,
}

const ShopAdminRouteWithChildren = ShopAdminRoute._addFileChildren(
  ShopAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ExploreRoute: ExploreRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProductIdRoute: ProductIdRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopAdminRoute: ShopAdminRouteWithChildren,
  ShopNewRoute: ShopNewRoute,
  UserAccountProfileRoute: UserAccountProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
